name: ReportUI
author: linuxthefish
website: https://github.com/syzolin/ReportUI

version: 1.3.2
api: 3.11.6

main: Taylcd\ReportUI\ReportUI
depend: ["FormAPI"]

commands:
  report:
    description: Report a player
    permission: report.use
  reportadmin:
    description: Open Report Panel
    permission: report.admin

permissions:
  report.use:
    default: true
  report.admin:
    default: op
  report.admin.notification:
    default: op
